### ISSUE TITLE
Task list for 3.0.0-beta

### ISSUE THREAD

**Issue by stucox** [Modernizr/v3.modernizr.com#1]
- [x] Fix [compatibility with old build URLs](https://github.com/Modernizr/Modernizr/issues/1275)
- [ ] Update docs a bit (not going to go too far here)
- [ ] Add more /\* DOC */ blocks to detects which currently lack them
- [ ] Add a news item about the beta
- [x] Add a “Try the v3 beta” kinda link to (v2) modernizr.com
- [x] Reinstate “download” button in builder with blob URL
- [x] Tidy up Generate / Download button styling
- [x] “Hide unselected” checkbox on builder to make it easier to see what’s in the current config
- [ ] Fix fonts – TypeKit’s 403ing

**Comment by ryanseddon** [comment]
![hide-unselected](https://cloud.githubusercontent.com/assets/143402/5886140/781380ee-a3df-11e4-8b6e-e6d1f8427987.gif)

**Comment by ryanseddon** [comment]
Build failed not sure what's up with that, jekyll runs fine on my local.

**Comment by ryanseddon** [comment]
I'm not seeing this 403 typekit issue is this already fixed?

**Comment by akrawchyk** [comment]
I'd like to help knock out some of those tasks. Which would be a good start?

**Comment by akrawchyk** [comment]
@ryanseddon @stucox can you recommend a place for me to start working on the tasks to complete this PR?
